# Generated by scripts/release.py (release-kit) from the v2026.9.2 release — do not edit.
class Fingerprint < Formula
  desc "Winnowing document fingerprinting and Jaccard similarity — detect duplicated logic"
  homepage "https://github.com/grahambrooks/fingerprint-rs"
  version "2026.9.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/fingerprint-rs/releases/download/v2026.9.2/fingerprint-v2026.9.2-aarch64-apple-darwin.tar.gz"
      sha256 "2e2a07d0229684fb9b243b2f91d9ce2179495a1c7a2e04fd59d95164862b649f"
    end
    on_intel do
      url "https://github.com/grahambrooks/fingerprint-rs/releases/download/v2026.9.2/fingerprint-v2026.9.2-x86_64-apple-darwin.tar.gz"
      sha256 "2c9e212e51278be8e837c80405292975a4334daf345ee3c1be31dbf4330f3504"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/fingerprint-rs/releases/download/v2026.9.2/fingerprint-v2026.9.2-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "a8104b2988626ea0b9ce661e4db700f155eb6dad5ddf10c8e1353f37c657f8ca"
    end
    on_intel do
      url "https://github.com/grahambrooks/fingerprint-rs/releases/download/v2026.9.2/fingerprint-v2026.9.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "b7f2b1572e57de66f12c497bcb58be660f26b4b4832ebf480cfc83db43c2d76a"
    end
  end

  def install
    bin.install "fingerprint"
  end

  test do
    assert_path_exists bin/"fingerprint"
  end
end
