# Generated by scripts/release.py (release-kit) from the v2026.10.1 release — do not edit.
class Fingerprint < Formula
  desc "Winnowing document fingerprinting and Jaccard similarity — detect duplicated logic"
  homepage "https://github.com/grahambrooks/fingerprint-rs"
  version "2026.10.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/fingerprint-rs/releases/download/v2026.10.1/fingerprint-v2026.10.1-aarch64-apple-darwin.tar.gz"
      sha256 "6a18a571a909ae048ec7eb1e7ded89717840367dfecaca8a9fc9ee3d025a49cb"
    end
    on_intel do
      url "https://github.com/grahambrooks/fingerprint-rs/releases/download/v2026.10.1/fingerprint-v2026.10.1-x86_64-apple-darwin.tar.gz"
      sha256 "3a63e0d4d63e030952be250fd9482ef1426baa0bbd50ef8b74c33a20b12649f3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/fingerprint-rs/releases/download/v2026.10.1/fingerprint-v2026.10.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "83a8b45ae788377858225a807ffac648a817222a041be7a7db549a5016aa484d"
    end
    on_intel do
      url "https://github.com/grahambrooks/fingerprint-rs/releases/download/v2026.10.1/fingerprint-v2026.10.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "d6641dbc94fc368c0ffa940e58e04a2902a936d1c8d883495b96a448b3c77f17"
    end
  end

  def install
    bin.install "fingerprint"
  end

  test do
    assert_path_exists bin/"fingerprint"
  end
end
